# Generated by Django 5.2 on 2025-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaspectsentiment',
            old_name='sentiment',
            new_name='sentiment_score',
        ),
        migrations.RemoveField(
            model_name='companyaspectsentiment',
            name='sentiment_type',
        ),
        migrations.AddField(
            model_name='companyaspectsentiment',
            name='sentiment_label',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Positive', 'Positive'), ('Negative', 'Negative')], default='Neutral', max_length=10),
        ),
    ]
