# Generated by Django 5.2 on 2025-05-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='followers', to='sentiment.company'),
        ),
    ]
